<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cenario200</name>
  <uuid>88b492cb-699d-473b-9b93-1d61d5ccc8f2</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[se
	Resultado_tabela é "200" 
então
	atribuir à decisão o valor "Reprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
