<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cenario400</name>
  <uuid>7660958c-59aa-46a3-a95b-e9e43f0924f0</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[se
	Resultado_tabela é "400" 
então
	atribuir à decisão o valor "Reprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
