<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cenario200prime</name>
  <uuid>628181bf-2bea-4aea-80ad-9ab19e0edd78</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[se
	Resultado_tabela é "200"
	e Prime 
então
	atribuir à decisão o valor "Gerente de renegociação precisa aprovar" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
