<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cenario200prime</name>
  <uuid>a0ea112b-3131-471c-94f2-2a805eaa1503</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[se
	Conversao_Media_Score é "200"
	e Prime 
então
	atribuir à decisão o valor verdadeiro ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
