<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a53831aa-43bf-4ba4-a034-25a41a048c3c</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[atribuir à decisão o valor falso ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
